[workspace]
authors = ["Val <saviorand@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "smokio"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025122405,<0.27"
