[workspace]
authors = ["Val <saviorand@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly", "https://repo.prefix.dev/modular-community"]
name = "smokio"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "smokio"
version = "26.1.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "*" }


[package.host-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"

[package.build-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"

[package.run-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.1.0.dev2025122405,<0.27"
